### ISSUE TITLE
Would the AGAGD documentation be better placed on an external service?

### ISSUE THREAD

**Issue by EarthSchlange** [usgo/agagd#167]
## Summary
There are a few documents within /docs file which provide a general startup guide. Additionally, we have two documentation pages https://agagd.usgo.org/information/ and https://agagd.usgo.org/qualifications/ which may be better served externally and may be easier to manage in markdown.

## Question
* Would the AGAGD documentation be better placed on an external service like https://readthedocs.org?

## Describe the feature you'd like to see on the AGAGD.
Documentation pages formatted in markdown and potentially deploy to another service instead of directly within the AGAGD application.  There is also the ability to move the documentation to a url like "docs.agagd.usgo.org" for example.

@vash3g @duckpunch thoughts?

**Comment by duckpunch** [comment]
> may be easier to manage in markdown.

Hm.  This is a good point, but how often do they change?  If they change often, Markdown seems like it would improve life.  If not, 🤷 .

> Would the AGAGD documentation be better placed on an external service like https://readthedocs.org?

For the info and qualification pages, it seems appropriate where it's at since our audience might be people who are essentially trying to update what they see on AGAGD.  As an aside, we could also add some content about when a TD can expect to see ratings updated.

All that said, I don't feel very strongly about keeping them in the app, so if you have a vision for moving it, I'm happy to roll with it.

For the repo/dev docs in `/docs`, that seems reasonable to keep in the repo.  If we're looking to make it look nicer, then yeah, something like readthedocs could work.  Alternatively, we could also use [GitHub Pages](https://pages.github.com/).

**Comment by EarthSchlange** [comment]
> All that said, I don't feel very strongly about keeping them in the app, so if you have a vision for moving it, I'm happy to roll with it.
I don't really have a vision for moving things anywhere at the moment. I am just curious.

> For the repo/dev docs in /docs, that seems reasonable to keep in the repo. If we're looking to make it look nicer, then yeah, something like readthedocs could work. Alternatively, we could also use [GitHub Pages](https://pages.github.com/).

Good idea with [Github Pages](https://pages.github.com/); I forgot about this. Changing our documentation may depend on how much movement there is on documentation issues like: #160 #161, if we get other documentation issues or need a cleaner place for our docs.

**Comment by EarthSchlange** [comment]
Closing. Question answered.
