### ISSUE TITLE
Add mechanism to deny auto-scraping of information

### ISSUE THREAD

**Issue by vash3g** [usgo/agagd#67]
We have people using this to scrape information. It would be nice to disable that to reduce some stress on the server.

**Comment by duckpunch** [comment]
> We have people using this to scrape information.

How?  And what are you suggesting to fix this?

**Comment by vash3g** [comment]
I dont know how theyre doing it but I have heard of at least three different people who have done so. AGA is happy to work with people on projects to relay data to people. We did so with OGS when they asked for game data. I dont know the best way to do so so I left it open.

**Comment by duckpunch** [comment]
Probably not the best "Good First Issue" :P

People scraping games data is unavoidable since it's just available publicly on the web.

**Comment by EarthSchlange** [comment]
@vash3g like @duckpunch says,

> People scraping games data is unavoidable since it's just available publicly on the web.

I am not sure we are actually experiencing server downtime or stress due to this.

Side note: the AGA board has scraped data for tournament participation,
* https://www.usgo.org/sites/default/files/boardminutes/AGA%20Board%20Minutes%209-8-2019.pdf, pg. 29, pg. 33

* https://docs.google.com/spreadsheets/d/e/2PACX-1vTPchBCqy64zjq1N3ZoZ7anAFE7fYDYFCbur5y8DdIVsE5QMU2i2JZs8mE-Ikx1x-Bii752HgwuFl79/pubchart?oid=1242758976&format=interactive
 
![Screenshot from 2021-02-15 01-08-25](https://user-images.githubusercontent.com/5054653/107926366-78260800-6f2a-11eb-9a82-e2ed3231ada1.png)

**Comment by EarthSchlange** [comment]
Closing. If we do see an issue which causes our servers to run in to problems, we can look at addressing this then.
